In [1]:
import numpy as np

In [2]:
# The Basics

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
 b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# get dimensions

b.ndim

2

In [9]:
# get shape
b.shape

(2, 3)

In [11]:
# get type

b.dtype

dtype('float64')

In [13]:
# get size

b.itemsize

8

In [14]:
# Get total size

a.size * a.itemsize

12

In [16]:
# get total size in another way

b.nbytes

48

In [17]:
# Accessing / Changing specific elements, rows, columns etc

a = np.array([[1, 2,3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a.shape

(2, 7)

In [22]:
# Get specific element [row number, column number]
a[1, -1]


14

In [25]:
# Get specific row
a [0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 5]

In [30]:
# Getting a little more fancy [row_number, startindex : endindex : stepsize]
a[1, 1: -1: 2]

array([ 9, 11, 13])

In [31]:
# appending array [row_number, index]

a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


# Getting into 3D


In [34]:
b = np.array ([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# getting specific element (work outside in)

b [0, 1,1]

4

In [39]:
# replace (dimensions needs to be same)

b[:, 1, :] = [[9, 9], [8, 8]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing different type of arrays


In [49]:
# All 0s matrix 

np.zeros((3, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
# All 1s matrix
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [52]:
# Any other number
np.full ((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [56]:
# Any other number (full_like)

np.full_like(b, 6)

array([[[6, 6],
        [6, 6]],

       [[6, 6],
        [6, 6]]])

In [58]:
# Random decimal numbers

np.random.rand(4,2,3)


array([[[0.61435374, 0.12215645, 0.78739331],
        [0.9388546 , 0.54515307, 0.58752546]],

       [[0.97897766, 0.19209596, 0.41616852],
        [0.88662427, 0.5467445 , 0.46564414]],

       [[0.94884175, 0.56174227, 0.30876737],
        [0.6552724 , 0.48758   , 0.07376532]],

       [[0.74105026, 0.25587476, 0.26533372],
        [0.04451455, 0.69595646, 0.47405836]]])

In [62]:
# Random decimal numbers in the shape like

np.random.random_sample(b.shape)

array([[[0.26338296, 0.87126181],
        [0.49439774, 0.30373527]],

       [[0.37827589, 0.44110057],
        [0.55139999, 0.52342395]]])

In [63]:
# Random integer values

np.random.randint(-2, 5, size = (3,4))

array([[ 1,  1,  3,  2],
       [-2, -2, -2, -2],
       [ 0,  3,  4,  0]])

In [2]:
# The identity Matrix (requires only one parameter because it's by nature a square matrix)
import numpy as np
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
# Repeat an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
output = np.ones((5,5))
print (output)

zero = np.zeros((3,3))
zero[1,1] = 9
print(zero)

output[1:-1,1:-1] = zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!


In [15]:
a = np.array([1,2,3])
b = a.copy()
b [0] = 100

print(a)

[1 2 3]


### Mathematics


In [17]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [18]:
a +2

array([3, 4, 5, 6])

In [19]:
a - 2

array([-1,  0,  1,  2])

In [20]:
a * 2

array([2, 4, 6, 8])

In [21]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [22]:
b = np.array([1, 0, 1, 0])

a + b

array([2, 2, 4, 4])

In [27]:
a ** 2

array([ 1,  4,  9, 16])

In [31]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [32]:
# take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [39]:
a = np.ones((3,4))
print(a)

b = np.full((4,3), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [45]:
# Find the determinant

c = np.identity(3)
np.linalg.det(c)


1.0

#### Statistics with numpy

In [46]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.min(stats, axis = 1)

array([1, 4])

In [51]:
np.max(stats, axis = 1)

array([3, 6])

In [52]:
np.sum(stats)

21

In [54]:
np.sum(stats, axis = 1)

array([ 6, 15])

In [55]:
np.sum(stats, axis = 0)

array([5, 7, 9])

# Re-organizing Arrays

In [70]:
before = np.array ([[1,2,3,4], [5,6,7,8]])

print(before)

after = before.reshape((2, 2, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Vertically stacking vectors

In [73]:
v1 = np.array([1,2,3,4])
v2 = np.array([5, 6,7,8])

np.vstack ([v1, v2, v1, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [76]:
### Horizentally stack 

h1 = np.ones((2, 4))
h2 = np.zeros((2,2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load from file

In [99]:
import pandas as pd
import numpy as np
import os


#to get the current directory for file
os.getcwd()

'C:\\Users\\SANJEEV'

In [102]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advance Indexing

In [104]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [103]:
filedata [filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [106]:
# indexs with a list in Numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,-2]]

array([2, 3, 8])

In [109]:
# any data that is > 50 vertical search

np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [110]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [111]:
# ~ means not 

(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [118]:
# creating an array and reshaping

arr = np.arange(1, 31)
print(arr)

arr = arr.reshape(6, 5)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [120]:
#indexing from the array 
##The slicing notation arr[2:4, 0:2] will return a subarray of arr containing rows with indices 2 and 3, and columns with indices 0 and 1.

#In other words, it will return a 2x2 subarray consisting of the elements in rows 2 and 3, and columns 0 and 1 of the original arr array.

arr[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [130]:
# slicing diagonally

arr[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [133]:
arr[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])